### ISSUE TITLE
Implement a New Scalable GWAS Diagram utilizing the Existing SVG Diagram UI

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-ui#389]
The next iteration of the Diagram must be scalable, 
The page loading should be robust for 2x more associations
The impact of Diagram generation on the data release must be minimised 

- [ ] Utilize the present SVG User interface alone 
- [ ] Investigate & understand how the data is plotted on the UI 
- [ ] Ascertain the possibility of retrieveing the data using a new and scalable approach
- [ ] Retire the Old pussycat 
- [ ] Retire the old virtuoso Infrastructure and other supporting technologies (OWL, RDF, ...)
- [ ] Retire the Old GWAS Diagram Data Release technologies 
- [ ] Use a new approach to generate and present the same data for the SVG Diagram
